---

name: Pull Request Actions

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Set up Black
        uses: psf/black@stable
        with:
          options: ". --check --line-length 100"
          version: "~=23.3.0"

  docker-image-push:
    runs-on: ubuntu-latest
    name: Create staging docker image
    steps:
     - name: Check out git repository
       uses: actions/checkout@v3

     - name: Extract branch name and remove illegal chars
       id: get_branch_name
       shell: bash
       run: echo "branch=$(echo "$(tr "/" "-" <<<${GITHUB_REF#refs/heads/})")" >> $GITHUB_ENV

     - name: Login to Docker Hub
       uses: docker/login-action@v2
       with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}

     - name: Set up Docker Buildx
       id: buildx
       uses: docker/setup-buildx-action@v2

     - name: Build and push
       id: docker_build
       uses: docker/build-push-action@v3
       with:
         context: ./
         file: ./Dockerfile
         push: true
         tags: "clinicalgenomics/arnold-stage:${{steps.get_branch_name.outputs.branch}}, clinicalgenomics/arnold-stage:latest"

  tests-coverage:
    runs-on: ubuntu-latest
    name: Test and coveralls
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Check out arnold
        uses: actions/checkout@v2
        with:
          repository: "Clinical-Genomics/arnold"

      - name: Install arnold dependencies
        run: |
          pip install -r requirements.txt -r requirements-dev.txt .

      - name: Install coveralls dependencies
        run: |
          pip install pytest-cov coveralls

      - name: Test with pytest & Coveralls
        run: |
          pytest --cov=arnold/
          coveralls
        env:
          GITHUB: 1
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
